name: hiepnx_timer
description: A new Flutter project.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.3+4
  provider: ^4.3.0
  path_provider: ^1.6.5
  easy_localization: ^2.3.2
  datetime_picker_formfield: ^1.0.0
  toast: ^0.1.5
  share: ^0.6.4+2
  open_appstore: ^1.0.2
  app_review: ^2.0.1
  launch_review: ^2.0.0
  flutter_local_notifications: ^1.4.4+2
  permission_handler: ^5.0.1+1
  url_launcher: ^5.0.2
  http: ^0.12.2
  flutter_time_picker_spinner: ^1.0.6+1

  audioplayers: ^0.17.3
  connectivity: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
